# Generated by Django 2.2.5 on 2019-11-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
