# Generated by Django 2.2.5 on 2019-11-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_first_app', '0002_auto_20191102_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='task_desc',
            field=models.CharField(default='No description for the task', max_length=264),
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
