# Generated by Django 2.2.5 on 2019-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_first_app', '0003_auto_20191102_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_desc',
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateField(default='2019-11-03'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2019-11-03'),
        ),
    ]
