# Generated by Django 2.2.5 on 2019-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_first_app', '0006_auto_20191104_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='No description here!'),
        ),
    ]
