# Generated by Django 2.2.5 on 2019-11-06 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_first_app', '0011_auto_20191106_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 6, 11, 11, 51, 96472)),
        ),
    ]
