# Generated by Django 2.2.5 on 2019-11-06 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_first_app', '0012_auto_20191106_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 6, 11, 12, 37, 410126, tzinfo=utc)),
        ),
    ]
