# Generated by Django 2.2.5 on 2019-11-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_first_app', '0014_auto_20191106_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2019-11-06'),
        ),
    ]
