# Generated by Django 2.2.5 on 2019-11-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_first_app', '0015_auto_20191106_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2019-11-07'),
        ),
    ]
